name: Publish Release

on:
  release:
    types: [published]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.repository == 'Akii/commercetools-sdk-java-v2-custom-types'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Release new version
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository publishPlugins -Pversion=${GITHUB_REF#"refs/tags/v"}
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          PGP_SIGN_KEY: ${{ secrets.PGP_SIGN_KEY }}
          PGP_SIGN_PASSPHRASE: ${{ secrets.PGP_SIGN_PASSPHRASE }}
          SONATYPE_PUBLISH_PASSWORD: ${{ secrets.SONATYPE_PUBLISH_PASSWORD }}
          SONATYPE_PUBLISH_USERNAME: ${{ secrets.SONATYPE_PUBLISH_USERNAME }}